### ISSUE TITLE
colors!

### ISSUE THREAD

**Issue by zartan9** [daniel-munro/pbnify#9]
hi is there a way to limit #s? for instance not have so many 2s ? also is the result available for commercial purposes? thanks~!

**Comment by daniel-munro** [comment]
Currently the only way to limit one of the palette colors/numbers is to go back and update the palette to select other colors that are similar to that color. Since regions of the image are assigned to the palette color most similar to the average color of the region, this will result in more regions being assigned to those similar palette colors instead of the single color.

Yes, you may use the outlines etc. produced by PBNify for commercial purposes, as long as it doesn't infringe on the original image's copyright.

**Comment by zartan9** [comment]
great thank you!
![nf](https://user-images.githubusercontent.com/74879950/229961419-e51fb456-c206-4965-92a1-e65478f87fe7.png)
ps  i cant find button now?

**Comment by daniel-munro** [comment]
It looks like you haven't selected any palette colors yet. At least two colors need to be chosen before you can run it.

**Comment by zartan9** [comment]
got it thanks again!
